title: HaileyBot
description: The HaileyBot Discord Bot

domain: "https://haileybot.github.io"
url: "https://haileybot.github.io"

destination: docs

encoding: utf-8

markdown: kramdown

kramdown:
  auto_ids: true

sass:
  sass_dir: _sass
  style: compressed

collections_dir: _collections
collections:
  index:
    output: true
    permalink: /:name
